[package]
name = "zstd"
version = "0.1.0"
edition = "2021"

authors = [ "Marthinus Scholtz <mscholtz@protonmail.com>" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zephyr = { path = "zephyr"}